# Generated by Django 3.2.3 on 2021-06-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='', help_text='제목을 입력해주세요.', max_length=100),
        ),
    ]
