# Generated by Django 3.2.3 on 2021-06-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='content',
            field=models.TextField(help_text='내용을 입력해주세요.'),
        ),
    ]
