# Generated by Django 3.2.3 on 2021-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
